name: Android Build (Capacitor)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  NODE_VERSION: 20.19.5
  PNPM_VERSION: 9

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install deps
        run: |
          pnpm i || true
          pnpm -C webwallet i --frozen-lockfile

      # IMPORTANT: build untuk Android -> JANGAN set BUILD_TARGET=pages
      - name: Build web (Android target)
        run: pnpm -C webwallet build

      - name: Capacitor sync (Android)
        run: pnpm -C webwallet cap sync android

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Cache Gradle agar build lebih cepat
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # ---------- RELEASE SIGNING (opsional) ----------
      # Step-step berikut hanya dijalankan jika secret keystore tersedia.
      - name: Decode keystore
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > webwallet/android/app/keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Configure signing
        if: ${{ secrets.KEY_ALIAS != '' && secrets.KEY_PASSWORD != '' && secrets.KEYSTORE_PASSWORD != '' }}
        run: |
          {
            echo "MY_KEYSTORE_FILE=keystore.jks"
            echo "MY_KEY_ALIAS=${{ secrets.KEY_ALIAS }}"
            echo "MY_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}"
            echo "MY_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}"
          } >> webwallet/android/gradle.properties

      # ---------- BUILD DEBUG ----------
      - name: Build APK (debug)
        working-directory: webwallet/android
        run: ./gradlew assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: safeid-wallet-debug-apk
          path: webwallet/android/app/build/outputs/apk/debug/app-debug.apk

      # ---------- BUILD RELEASE (opsional; butuh keystore) ----------
      - name: Build APK (release)
        if: ${{ secrets.KEYSTORE_BASE64 != '' && secrets.KEY_ALIAS != '' && secrets.KEY_PASSWORD != '' && secrets.KEYSTORE_PASSWORD != '' }}
        working-directory: webwallet/android
        run: ./gradlew assembleRelease

      - name: Upload release APK
        if: ${{ success() && secrets.KEYSTORE_BASE64 != '' && secrets.KEY_ALIAS != '' && secrets.KEY_PASSWORD != '' && secrets.KEYSTORE_PASSWORD != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: safeid-wallet-release-apk
          path: webwallet/android/app/build/outputs/apk/release/app-release.apk
