name: Android Build (Capacitor)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  NODE_VERSION: 20.19.5
  PNPM_VERSION: 9

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: webwallet/pnpm-lock.yaml

      - name: Cleanup workspace files
        run: |
          rm -f pnpm-workspace.yaml || true
          rm -f webwallet/pnpm-workspace.yaml || true

      - name: Install deps (webwallet only)
        working-directory: webwallet
        run: pnpm install --frozen-lockfile=false

      - name: Build web
        working-directory: webwallet
        run: pnpm build

      - name: Capacitor sync (Android)
        working-directory: webwallet
        run: pnpm cap sync android

      # Toolchain: cocok dengan app/build.gradle (Java/Kotlin target 17)
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      # gradlew sudah executable di repo, tapi tetap aman untuk runner
      - name: Make gradlew executable
        working-directory: webwallet/android
        shell: bash
        run: chmod +x gradlew

      # ---------- RELEASE SIGNING (opsional) ----------
      - name: Check keystore secret
        id: has_keystore
        shell: bash
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          if [ -n "${KEYSTORE_BASE64}" ]; then
            echo "present=true" >> "$GITHUB_OUTPUT"
          else
            echo "present=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Decode keystore
        if: steps.has_keystore.outputs.present == 'true'
        shell: bash
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          set -euo pipefail
          mkdir -p webwallet/android/app
          # buang header/footer PEM & CRLF/spasi lalu decode
          printf '%s' "${KEYSTORE_BASE64}" \
            | sed -E 's/-----BEGIN[^-]*-----//g; s/-----END[^-]*-----//g' \
            | tr -d '\r\n ' \
            | base64 -d -i > webwallet/android/app/keystore.jks
          # verifikasi cepat
          keytool -list -keystore webwallet/android/app/keystore.jks -storepass "${{ secrets.KEYSTORE_PASSWORD }}" >/dev/null 2>&1

      - name: Configure signing
        if: steps.has_keystore.outputs.present == 'true'
        working-directory: webwallet/android
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          {
            echo "MY_KEYSTORE_FILE=app/keystore.jks"
            echo "MY_KEY_ALIAS=${KEY_ALIAS}"
            echo "MY_KEY_PASSWORD=${KEY_PASSWORD}"
            echo "MY_STORE_PASSWORD=${KEYSTORE_PASSWORD}"
          } >> gradle.properties

      # ---------- Build ----------
      - name: Build APK (debug)
        working-directory: webwallet/android
        run: ./gradlew assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: safeid-wallet-debug-apk
          path: webwallet/android/app/build/outputs/apk/debug/app-debug.apk

      - name: Build APK (release)
        if: steps.has_keystore.outputs.present == 'true'
        working-directory: webwallet/android
        run: ./gradlew assembleRelease

      - name: Upload release APK
        if: steps.has_keystore.outputs.present == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: safeid-wallet-release-apk
          path: webwallet/android/app/build/outputs/apk/release/app-release.apk

      # (Opsional) AAB untuk Play Store
      - name: Build AAB (release)
        if: steps.has_keystore.outputs.present == 'true'
        working-directory: webwallet/android
        run: ./gradlew bundleRelease

      - name: Upload release AAB
        if: steps.has_keystore.outputs.present == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: safeid-wallet-release-aab
          path: webwallet/android/app/build/outputs/bundle/release/app-release.aab
