name: Android Build (Capacitor)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  NODE_VERSION: 20.19.5
  PNPM_VERSION: 9

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: webwallet/pnpm-lock.yaml

      # (opsional) Pastikan tidak ada workspace pnpm yang nyasar
      - name: Remove stray workspace files
        run: |
          rm -f pnpm-workspace.yaml || true
          rm -f webwallet/pnpm-workspace.yaml || true

      - name: Install deps (only webwallet)
        working-directory: webwallet
        run: pnpm install --frozen-lockfile=false

      - name: Build web (Android target)
        working-directory: webwallet
        run: pnpm build

      - name: Capacitor sync (Android)
        working-directory: webwallet
        run: pnpm cap sync android

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      # ---------- RELEASE SIGNING (opsional) ----------
      - name: Decode keystore
        if: ${{ env.KEYSTORE_BASE64 != '' }}
        shell: bash
        run: |
          mkdir -p webwallet/android/app
          # hapus CRLF/spasi, decode; -i = ignore-garbage
          printf '%s' "${KEYSTORE_BASE64}" | tr -d '\r\n ' | base64 -d -i > webwallet/android/app/keystore.jks

      - name: Configure signing
        if: ${{ env.KEYSTORE_BASE64 != '' }}
        working-directory: webwallet/android
        run: |
          {
            echo "MY_KEYSTORE_FILE=keystore.jks"
            echo "MY_KEY_ALIAS=${KEY_ALIAS}"
            echo "MY_KEY_PASSWORD=${KEY_PASSWORD}"
            echo "MY_STORE_PASSWORD=${KEYSTORE_PASSWORD}"
          } >> gradle.properties

      # ---------- Build ----------
      - name: Build APK (debug)
        working-directory: webwallet/android
        run: ./gradlew assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: safeid-wallet-debug-apk
          path: webwallet/android/app/build/outputs/apk/debug/app-debug.apk

      - name: Build APK (release)
        if: ${{ env.KEYSTORE_BASE64 != '' }}
        working-directory: webwallet/android
        run: ./gradlew assembleRelease

      - name: Upload release APK
        if: ${{ env.KEYSTORE_BASE64 != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: safeid-wallet-release-apk
          path: webwallet/android/app/build/outputs/apk/release/app-release.apk
