name: Android Build (Capacitor)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  NODE_VERSION: 20.19.5
  PNPM_VERSION: 9

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install deps
        run: |
          pnpm i || true
          pnpm -C webwallet i --frozen-lockfile

      # IMPORTANT: build untuk Android -> JANGAN set BUILD_TARGET=pages
      - name: Build web (Android target)
        run: pnpm -C webwallet build

      - name: Capacitor sync (Android)
        run: pnpm -C webwallet cap sync android

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build APK (debug)
        working-directory: webwallet/android
        run: ./gradlew assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: safeid-wallet-debug-apk
          path: webwallet/android/app/build/outputs/apk/debug/app-debug.apk
