name: Android Build (Capacitor)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  NODE_VERSION: 20.19.5
  PNPM_VERSION: 9
  # Secrets dibaca ke ENV supaya mudah dipakai di langkah-langkah
  KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: webwallet/pnpm-lock.yaml

      # Bersihkan file workspace PNPM yang bisa memicu "packages field missing or empty"
      - name: Cleanup workspace files
        run: |
          rm -f pnpm-workspace.yaml || true
          rm -f webwallet/pnpm-workspace.yaml || true

      - name: Install deps (webwallet only)
        working-directory: webwallet
        run: pnpm install --frozen-lockfile=false

      - name: Build web (Android target)
        working-directory: webwallet
        run: pnpm build

      - name: Capacitor sync (Android)
        working-directory: webwallet
        run: pnpm cap sync android

      # AGP 8.13 → gunakan JDK 21 agar konsisten dengan compileOptions/jvmTarget
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      # ---------- Signing (opsional; aktif jika KEYSTORE_BASE64 terisi) ----------
      - name: Decode keystore
        if: ${{ env.KEYSTORE_BASE64 != '' }}
        shell: bash
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > webwallet/android/app/keystore.jks

      - name: Configure signing
        if: ${{ env.KEYSTORE_BASE64 != '' }}
        working-directory: webwallet/android
        run: |
          {
            echo "MY_KEYSTORE_FILE=app/keystore.jks"
            echo "MY_KEY_ALIAS=${KEY_ALIAS}"
            echo "MY_KEY_PASSWORD=${KEY_PASSWORD}"
            echo "MY_STORE_PASSWORD=${KEYSTORE_PASSWORD}"
          } >> gradle.properties

      # ---------- Build ----------
      - name: Build APK (debug)
        working-directory: webwallet/android
        run: ./gradlew assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: safeid-wallet-debug-apk
          path: webwallet/android/app/build/outputs/apk/debug/app-debug.apk

      - name: Build APK (release)
        if: ${{ env.KEYSTORE_BASE64 != '' }}
        working-directory: webwallet/android
        run: ./gradlew assembleRelease

      - name: Upload release APK
        if: ${{ env.KEYSTORE_BASE64 != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: safeid-wallet-release-apk
          path: webwallet/android/app/build/outputs/apk/release/app-release.apk

      # (Opsional) Build AAB untuk Play Store
      - name: Build AAB (release)
        if: ${{ env.KEYSTORE_BASE64 != '' }}
        working-directory: webwallet/android
        run: ./gradlew bundleRelease

      - name: Upload release AAB
        if: ${{ env.KEYSTORE_BASE64 != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: safeid-wallet-release-aab
          path: webwallet/android/app/build/outputs/bundle/release/app-release.aab
