name: CI

on:
  pull_request:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm lint || true
      - run: pnpm test --if-present
      - run: pnpm -C webwallet build || pnpm build --if-present
