name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_VERSION: 20
  PNPM_VERSION: 9

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install dependencies
      - name: Install deps (root)
        run: pnpm install --frozen-lockfile=false

      - name: Install deps (webwallet)
        run: pnpm -C webwallet install --frozen-lockfile=false

      # Lint / Test opsional
      - name: Lint
        run: pnpm -C webwallet lint || true

      - name: Test
        run: pnpm -C webwallet test --if-present || true

      # Build check
      - name: Build webwallet
        run: pnpm -C webwallet build
