name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  NODE_VERSION: 20
  PNPM_VERSION: 9

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node (pnpm cache → webwallet lockfile)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: |
            webwallet/pnpm-lock.yaml

      - name: Install deps (root)
        run: pnpm i || true

      - name: Install deps (webwallet)
        run: pnpm -C webwallet i --frozen-lockfile

      - name: Lint (skip if not present)
        run: pnpm -C webwallet lint || true

      - name: Test (skip if not present)
        run: pnpm -C webwallet test --if-present || true

      - name: Build (verifikasi build)
        run: pnpm -C webwallet build
