name: Cleanup old workflow runs (Mattraks)

on:
  schedule:
    - cron: "0 0 * * *"   # tiap hari 00:00 UTC
  workflow_dispatch:

permissions:
  actions: write
  contents: read

env:
  RETAIN_DAYS: "1"                       # hapus run yang lebih tua dari N hari
  KEEP_MIN_RUNS: "3"                     # minimal sisakan N run terbaru per workflow
  DELETE_CONCLUSIONS: "failure,cancelled,timed_out"  # target status untuk dihapus

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: ${{ env.RETAIN_DAYS }}
          keep_minimum_runs: ${{ env.KEEP_MIN_RUNS }}
          branch: main
          delete_run_by_conclusion: true
          conclusion: ${{ env.DELETE_CONCLUSIONS }}
