name: Cleanup old workflow runs (Mattraks)

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0            # hapus semua yang lebih tua dari 0 hari (praktis: nonaktifkan batas usia)
          keep_minimum_runs: 10     # tapi sisakan min. 10 run per workflow
          delete_workflow_by_state: "completed"   # hapus hanya run yang statusnya completed (bisa memuat success/failure)
          # branch: main            # (opsional) limit ke branch main
