name: Deploy Pages

on:
  push:
    branches: [ main ]        # deploy production
  pull_request:
    branches: [ main ]        # preview untuk PR

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_VERSION: 20
  PNPM_VERSION: 9
  BASE_PATH: /safeid-wallet/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION || 9 }}

      - id: find_lock
        shell: bash
        run: |
          if ls **/pnpm-lock.yaml 1>/dev/null 2>&1; then
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Node (with pnpm cache)
        if: steps.find_lock.outputs.found == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION || 20 }}
          cache: pnpm
          cache-dependency-path: |
            **/pnpm-lock.yaml

      - name: Setup Node (no cache)
        if: steps.find_lock.outputs.found != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION || 20 }}

      - name: Install deps (root)
        run: pnpm i || true

      - name: Install deps (webwallet)
        run: pnpm -C webwallet i --frozen-lockfile

      - name: Build webwallet
        env:
          BASE_PATH: ${{ env.BASE_PATH }}
          NODE_OPTIONS: --max-old-space-size=4096
        run: pnpm -C webwallet build

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: webwallet/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
