name: Sponsors (Realtime)

on:
  repository_dispatch:
    types: [sponsors_event]    # Cloudflare Worker
  workflow_dispatch: {}        # agar bisa dijalankan manual saat tes

permissions:
  contents: write

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm i graphql-request twitter-api-v2

      - name: Render SPONSORS.md & patch README
        env:
          GH_TOKEN: ${{ secrets.GH_SPONSORS_TOKEN }}
          GH_LOGIN: "EndiHariadi43"
          EVENT_ACTION: ${{ github.event.client_payload.action }}
          EVENT_TIER: ${{ github.event.client_payload.tierName }}
          EVENT_SPONSOR: ${{ github.event.client_payload.sponsor }}
          EVENT_PRIVACY: ${{ github.event.client_payload.privacy || 'PUBLIC' }}
        run: node .github/scripts/render-sponsors.js

      # --- ONE-TIME: $10 Twitter shoutout ---
      - name: Tweet for $10 one-time
        if: ${{ github.event.client_payload.isOneTime && (contains(github.event.client_payload.tierName, 'Twitter Shoutout') || contains(github.event.client_payload.tierName, '10') || github.event.client_payload.amountCents == 1000) }}
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          EVENT_SPONSOR: ${{ github.event.client_payload.sponsor }}
          EVENT_PRIVACY: ${{ github.event.client_payload.privacy || 'PUBLIC' }}
        run: node .github/scripts/post-twitter.js

      # --- ONE-TIME: $50 Release notes mention ---
      - name: Queue Release Notes for $50 one-time
        if: ${{ github.event.client_payload.isOneTime && (contains(github.event.client_payload.tierName, 'Release Notes') || contains(github.event.client_payload.tierName, '50') || github.event.client_payload.amountCents == 5000) }}
        env:
          EVENT_SPONSOR: ${{ github.event.client_payload.sponsor }}
          EVENT_PRIVACY: ${{ github.event.client_payload.privacy || 'PUBLIC' }}
        run: node .github/scripts/append-release-note.js

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: sponsors realtime update"
            git push
          fi
